version: "3.9"

services:
  db:
    image: postgres
    volumes:
      # Means that the files in sql will be run whenever ./data/db is not present
      # If you want to refresh the schema (and delete current data)
      # delete ./data/db
      - ./sql:/docker-entrypoint-initdb.d
      # This is a a persistent store of PSQL data for development
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=toor
